services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static/dist
    networks:
      - app-network

  www:
    build:
      context: .
      dockerfile: docker/www/Dockerfile
    command: ["pnpm", "dirt-dev"]
    ports:
      - "5173:5173"
    volumes:
      - .:/app/src
      - static_volume:/app/src/static/dist
      - node_modules:/app/src/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:
  static_volume:
  node_modules: